<a href="https://colab.research.google.com/github/Lokesh-ctr/23CSBTB29/blob/main/Aiml%20lab3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
arr=np.array([5,1,4,6])
np.sort(arr)

array([1, 4, 5, 6])

In [2]:
import numpy as np
a=np.array([1,2,3])
b=np.array([5,6,7])
c=(a+b)
print(c)

[ 6  8 10]


In [3]:
import numpy as np
a=np.array([4,5,6])
b=np.array([7,8,9])
c=(a-b)
print(c)

[-3 -3 -3]


In [4]:
import numpy as np
a=np.array([3,4,5])
b=np.array([4,5,6])
c=(a*b)
print(c)

[12 20 30]
