<a href="https://colab.research.google.com/github/Lokesh-ctr/23CSBTB29/blob/main/Array(1d%2C2d%2C3d).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
a=np.array([[1,2,3],[32,6,8]])
print(a)

[[ 1  2  3]
 [32  6  8]]


In [2]:
import numpy as np
a=np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
import numpy as np
l=[[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]],[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]]
a=np.array(l)
print(a)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]

 [[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
